# Generated by Django 5.1.8 on 2025-04-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='periodic_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='rd_task.task'),
        ),
    ]
