# Generated by Django 5.1.8 on 2025-04-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_task', '0002_taskschedule_periodic_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='rd_task.task'),
        ),
    ]
