# Generated by Django 5.1.8 on 2025-04-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('rd_task', '0003_alter_taskresult_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='periodic_task_id',
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='interval_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='interval',
            field=models.IntegerField(help_text='The interval in seconds for periodic tasks'),
        ),
    ]
